# Generated by Django 3.1.7 on 2021-03-25 11:48

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('distanceReq', models.IntegerField(default=100)),
                ('orgAddr', models.CharField(default='address', max_length=1000)),
                ('orgName', models.CharField(default='org name', max_length=100)),
                ('orgContact', models.CharField(default='0000000000', max_length=13)),
                ('expiration', models.DateField(null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(default='emp name', max_length=50)),
                ('designation', models.CharField(default='designation', max_length=50)),
                ('salary', models.IntegerField(default=10000)),
                ('loc', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('for_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('loginTime', models.CharField(default='null', max_length=5)),
                ('logoutTime', models.CharField(default='null', max_length=5)),
                ('for_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.employee')),
                ('for_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('txt', models.CharField(default='announcement', max_length=5000)),
                ('for_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.organisation')),
            ],
        ),
    ]
