# Generated by Django 3.1.7 on 2021-03-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='contact',
            field=models.CharField(default='0000000000', max_length=13),
        ),
    ]
