# Generated by Django 3.1.7 on 2021-03-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20210325_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='imei',
            field=models.CharField(default='', max_length=200),
        ),
    ]
