# Generated by Django 3.1.7 on 2021-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_employee_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='imei',
            field=models.CharField(default='x', max_length=200),
        ),
    ]
