# Generated by Django 3.1.7 on 2021-03-26 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20210326_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='status',
            field=models.CharField(default='halfday', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='half_day',
            field=models.CharField(default='10:15', max_length=5),
        ),
        migrations.AddField(
            model_name='organisation',
            name='leave',
            field=models.CharField(default='15:00', max_length=5),
        ),
        migrations.AddField(
            model_name='organisation',
            name='punchOutTime',
            field=models.CharField(default='19:00', max_length=5),
        ),
        migrations.CreateModel(
            name='attendenceReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.BooleanField(default=False)),
                ('for_att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.attendence')),
            ],
        ),
    ]
