# Generated by Django 3.1.7 on 2021-03-27 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_auto_20210327_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendencereq',
            name='for_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.organisation'),
        ),
    ]
