# Generated by Django 3.1.7 on 2021-03-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_attendencereq_for_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendencereq',
            name='for_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.organisation'),
        ),
    ]
