# Generated by Django 3.1.7 on 2021-03-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_personalmsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmsg',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
