# Generated by Django 3.1.7 on 2021-03-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_personalmsg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='totalEmp',
            field=models.IntegerField(default=20),
        ),
    ]
